-- Seed: 14 departamentos de El Salvador y sus municipios
-- Idempotente: no duplica si ya existen (usa ON CONFLICT DO NOTHING)

INSERT INTO departamentos (nombre)
VALUES
  ('Ahuachapán'),
  ('Cabañas'),
  ('Chalatenango'),
  ('Cuscatlán'),
  ('La Libertad'),
  ('La Paz'),
  ('La Unión'),
  ('Morazán'),
  ('San Miguel'),
  ('San Salvador'),
  ('San Vicente'),
  ('Santa Ana'),
  ('Sonsonate'),
  ('Usulután')
ON CONFLICT (nombre) DO NOTHING;

WITH municipios_seed (departamento, municipio) AS (
  VALUES
    -- Ahuachapán (12)
    ('Ahuachapán', 'Ahuachapán'),
    ('Ahuachapán', 'Apaneca'),
    ('Ahuachapán', 'Atiquizaya'),
    ('Ahuachapán', 'Concepción de Ataco'),
    ('Ahuachapán', 'El Refugio'),
    ('Ahuachapán', 'Guaymango'),
    ('Ahuachapán', 'Jujutla'),
    ('Ahuachapán', 'San Francisco Menéndez'),
    ('Ahuachapán', 'San Lorenzo'),
    ('Ahuachapán', 'San Pedro Puxtla'),
    ('Ahuachapán', 'Tacuba'),
    ('Ahuachapán', 'Turín'),

    -- Cabañas (9)
    ('Cabañas', 'Sensuntepeque'),
    ('Cabañas', 'Cinquera'),
    ('Cabañas', 'Dolores'),
    ('Cabañas', 'Guacotecti'),
    ('Cabañas', 'Ilobasco'),
    ('Cabañas', 'Jutiapa'),
    ('Cabañas', 'San Isidro'),
    ('Cabañas', 'Tejutepeque'),
    ('Cabañas', 'Victoria'),

    -- Chalatenango (33)
    ('Chalatenango', 'Chalatenango'),
    ('Chalatenango', 'Agua Caliente'),
    ('Chalatenango', 'Arcatao'),
    ('Chalatenango', 'Azacualpa'),
    ('Chalatenango', 'Cancasque'),
    ('Chalatenango', 'Citalá'),
    ('Chalatenango', 'Comalapa'),
    ('Chalatenango', 'Concepción Quezaltepeque'),
    ('Chalatenango', 'Dulce Nombre de María'),
    ('Chalatenango', 'El Carrizal'),
    ('Chalatenango', 'El Paraíso'),
    ('Chalatenango', 'La Laguna'),
    ('Chalatenango', 'La Palma'),
    ('Chalatenango', 'La Reina'),
    ('Chalatenango', 'Las Flores'),
    ('Chalatenango', 'Las Vueltas'),
    ('Chalatenango', 'Nombre de Jesús'),
    ('Chalatenango', 'Nueva Concepción'),
    ('Chalatenango', 'Nueva Trinidad'),
    ('Chalatenango', 'Ojos de Agua'),
    ('Chalatenango', 'Potonico'),
    ('Chalatenango', 'San Antonio de la Cruz'),
    ('Chalatenango', 'San Antonio Los Ranchos'),
    ('Chalatenango', 'San Fernando'),
    ('Chalatenango', 'San Francisco Lempa'),
    ('Chalatenango', 'San Francisco Morazán'),
    ('Chalatenango', 'San Ignacio'),
    ('Chalatenango', 'San Isidro Labrador'),
    ('Chalatenango', 'San José Cancasque'),
    ('Chalatenango', 'San José Las Flores'),
    ('Chalatenango', 'San Luis del Carmen'),
    ('Chalatenango', 'San Miguel de Mercedes'),
    ('Chalatenango', 'San Rafael'),
    ('Chalatenango', 'Santa Rita'),
    ('Chalatenango', 'Tejutla'),

    -- Cuscatlán (16)
    ('Cuscatlán', 'Cojutepeque'),
    ('Cuscatlán', 'Candelaria'),
    ('Cuscatlán', 'El Carmen'),
    ('Cuscatlán', 'El Rosario'),
    ('Cuscatlán', 'Monte San Juan'),
    ('Cuscatlán', 'Oratorio de Concepción'),
    ('Cuscatlán', 'San Bartolomé Perulapía'),
    ('Cuscatlán', 'San Cristóbal'),
    ('Cuscatlán', 'San José Guayabal'),
    ('Cuscatlán', 'San Pedro Perulapán'),
    ('Cuscatlán', 'San Rafael Cedros'),
    ('Cuscatlán', 'San Ramón'),
    ('Cuscatlán', 'Santa Cruz Analquito'),
    ('Cuscatlán', 'Santa Cruz Michapa'),
    ('Cuscatlán', 'Suchitoto'),
    ('Cuscatlán', 'Tenancingo'),

    -- La Libertad (22)
    ('La Libertad', 'Antiguo Cuscatlán'),
    ('La Libertad', 'Chiltiupán'),
    ('La Libertad', 'Ciudad Arce'),
    ('La Libertad', 'Colón'),
    ('La Libertad', 'Comasagua'),
    ('La Libertad', 'Huizúcar'),
    ('La Libertad', 'Jayaque'),
    ('La Libertad', 'Jicalapa'),
    ('La Libertad', 'La Libertad'),
    ('La Libertad', 'Nuevo Cuscatlán'),
    ('La Libertad', 'Quezaltepeque'),
    ('La Libertad', 'Sacacoyo'),
    ('La Libertad', 'San José Villanueva'),
    ('La Libertad', 'San Juan Opico'),
    ('La Libertad', 'San Matías'),
    ('La Libertad', 'San Pablo Tacachico'),
    ('La Libertad', 'Santa Tecla'),
    ('La Libertad', 'Talnique'),
    ('La Libertad', 'Tamanique'),
    ('La Libertad', 'Teotepeque'),
    ('La Libertad', 'Tepecoyo'),
    ('La Libertad', 'Zaragoza'),

    -- La Paz (22)
    ('La Paz', 'Zacatecoluca'),
    ('La Paz', 'Cuyultitán'),
    ('La Paz', 'El Rosario'),
    ('La Paz', 'Jerusalén'),
    ('La Paz', 'Mercedes La Ceiba'),
    ('La Paz', 'Olocuilta'),
    ('La Paz', 'Paraíso de Osorio'),
    ('La Paz', 'San Antonio Masahuat'),
    ('La Paz', 'San Emigdio'),
    ('La Paz', 'San Francisco Chinameca'),
    ('La Paz', 'San Juan Nonualco'),
    ('La Paz', 'San Juan Talpa'),
    ('La Paz', 'San Juan Tepezontes'),
    ('La Paz', 'San Luis La Herradura'),
    ('La Paz', 'San Luis Talpa'),
    ('La Paz', 'San Miguel Tepezontes'),
    ('La Paz', 'San Pedro Masahuat'),
    ('La Paz', 'San Pedro Nonualco'),
    ('La Paz', 'San Rafael Obrajuelo'),
    ('La Paz', 'Santa María Ostuma'),
    ('La Paz', 'Santiago Nonualco'),
    ('La Paz', 'Tapalhuaca'),

    -- La Unión (18)
    ('La Unión', 'La Unión'),
    ('La Unión', 'Anamorós'),
    ('La Unión', 'Bolívar'),
    ('La Unión', 'Concepción de Oriente'),
    ('La Unión', 'Conchagua'),
    ('La Unión', 'El Carmen'),
    ('La Unión', 'El Sauce'),
    ('La Unión', 'Intipucá'),
    ('La Unión', 'Lislique'),
    ('La Unión', 'Meanguera del Golfo'),
    ('La Unión', 'Nueva Esparta'),
    ('La Unión', 'Pasaquina'),
    ('La Unión', 'Polorós'),
    ('La Unión', 'San Alejo'),
    ('La Unión', 'San José'),
    ('La Unión', 'Santa Rosa de Lima'),
    ('La Unión', 'Yayantique'),
    ('La Unión', 'Yucuaiquín'),

    -- Morazán (26)
    ('Morazán', 'San Francisco Gotera'),
    ('Morazán', 'Arambala'),
    ('Morazán', 'Cacaopera'),
    ('Morazán', 'Chilanga'),
    ('Morazán', 'Corinto'),
    ('Morazán', 'Delicias de Concepción'),
    ('Morazán', 'El Divisadero'),
    ('Morazán', 'El Rosario'),
    ('Morazán', 'Gualococti'),
    ('Morazán', 'Guatajiagua'),
    ('Morazán', 'Joateca'),
    ('Morazán', 'Jocoaitique'),
    ('Morazán', 'Jocoro'),
    ('Morazán', 'Lolotiquillo'),
    ('Morazán', 'Meanguera'),
    ('Morazán', 'Osicala'),
    ('Morazán', 'Perquín'),
    ('Morazán', 'San Carlos'),
    ('Morazán', 'San Fernando'),
    ('Morazán', 'San Isidro'),
    ('Morazán', 'San Simón'),
    ('Morazán', 'Sensembra'),
    ('Morazán', 'Sociedad'),
    ('Morazán', 'Torola'),
    ('Morazán', 'Yamabal'),
    ('Morazán', 'Yoloaiquín'),

    -- San Miguel (20)
    ('San Miguel', 'San Miguel'),
    ('San Miguel', 'Carolina'),
    ('San Miguel', 'Chapeltique'),
    ('San Miguel', 'Chinameca'),
    ('San Miguel', 'Chirilagua'),
    ('San Miguel', 'Ciudad Barrios'),
    ('San Miguel', 'Comacarán'),
    ('San Miguel', 'El Tránsito'),
    ('San Miguel', 'Lolotique'),
    ('San Miguel', 'Moncagua'),
    ('San Miguel', 'Nueva Guadalupe'),
    ('San Miguel', 'Nuevo Edén de San Juan'),
    ('San Miguel', 'Quelepa'),
    ('San Miguel', 'San Antonio'),
    ('San Miguel', 'San Gerardo'),
    ('San Miguel', 'San Jorge'),
    ('San Miguel', 'San Luis de la Reina'),
    ('San Miguel', 'San Rafael Oriente'),
    ('San Miguel', 'Sesori'),
    ('San Miguel', 'Uluazapa'),

    -- San Salvador (19)
    ('San Salvador', 'San Salvador'),
    ('San Salvador', 'Aguilares'),
    ('San Salvador', 'Apopa'),
    ('San Salvador', 'Ayutuxtepeque'),
    ('San Salvador', 'Cuscatancingo'),
    ('San Salvador', 'Ciudad Delgado'),
    ('San Salvador', 'El Paisnal'),
    ('San Salvador', 'Guazapa'),
    ('San Salvador', 'Ilopango'),
    ('San Salvador', 'Mejicanos'),
    ('San Salvador', 'Nejapa'),
    ('San Salvador', 'Panchimalco'),
    ('San Salvador', 'Rosario de Mora'),
    ('San Salvador', 'San Marcos'),
    ('San Salvador', 'San Martín'),
    ('San Salvador', 'Santiago Texacuangos'),
    ('San Salvador', 'Santo Tomás'),
    ('San Salvador', 'Soyapango'),
    ('San Salvador', 'Tonacatepeque'),

    -- San Vicente (13)
    ('San Vicente', 'San Vicente'),
    ('San Vicente', 'Apastepeque'),
    ('San Vicente', 'Guadalupe'),
    ('San Vicente', 'San Cayetano Istepeque'),
    ('San Vicente', 'San Esteban Catarina'),
    ('San Vicente', 'San Ildefonso'),
    ('San Vicente', 'San Lorenzo'),
    ('San Vicente', 'San Sebastián'),
    ('San Vicente', 'Santa Clara'),
    ('San Vicente', 'Santo Domingo'),
    ('San Vicente', 'Tecoluca'),
    ('San Vicente', 'Tepetitán'),
    ('San Vicente', 'Verapaz'),

    -- Santa Ana (13)
    ('Santa Ana', 'Santa Ana'),
    ('Santa Ana', 'Candelaria de la Frontera'),
    ('Santa Ana', 'Chalchuapa'),
    ('Santa Ana', 'Coatepeque'),
    ('Santa Ana', 'El Congo'),
    ('Santa Ana', 'El Porvenir'),
    ('Santa Ana', 'Masahuat'),
    ('Santa Ana', 'Metapán'),
    ('Santa Ana', 'San Antonio Pajonal'),
    ('Santa Ana', 'San Sebastián Salitrillo'),
    ('Santa Ana', 'Santa Rosa Guachipilín'),
    ('Santa Ana', 'Santiago de la Frontera'),
    ('Santa Ana', 'Texistepeque'),

    -- Sonsonate (16)
    ('Sonsonate', 'Sonsonate'),
    ('Sonsonate', 'Acajutla'),
    ('Sonsonate', 'Armenia'),
    ('Sonsonate', 'Caluco'),
    ('Sonsonate', 'Cuisnahuat'),
    ('Sonsonate', 'Izalco'),
    ('Sonsonate', 'Juayúa'),
    ('Sonsonate', 'Nahuizalco'),
    ('Sonsonate', 'Nahulingo'),
    ('Sonsonate', 'Salcoatitán'),
    ('Sonsonate', 'San Antonio del Monte'),
    ('Sonsonate', 'San Julián'),
    ('Sonsonate', 'Santa Catarina Masahuat'),
    ('Sonsonate', 'Santa Isabel Ishuatán'),
    ('Sonsonate', 'Santo Domingo de Guzmán'),
    ('Sonsonate', 'Sonzacate'),

    -- Usulután (23)
    ('Usulután', 'Usulután'),
    ('Usulután', 'Alegría'),
    ('Usulután', 'Berlín'),
    ('Usulután', 'California'),
    ('Usulután', 'Concepción Batres'),
    ('Usulután', 'El Triunfo'),
    ('Usulután', 'Ereguayquín'),
    ('Usulután', 'Estanzuelas'),
    ('Usulután', 'Jiquilisco'),
    ('Usulután', 'Jucuapa'),
    ('Usulután', 'Jucuarán'),
    ('Usulután', 'Mercedes Umaña'),
    ('Usulután', 'Nueva Granada'),
    ('Usulután', 'Ozatlán'),
    ('Usulután', 'Puerto El Triunfo'),
    ('Usulután', 'San Agustín'),
    ('Usulután', 'San Buenaventura'),
    ('Usulután', 'San Dionisio'),
    ('Usulután', 'San Francisco Javier'),
    ('Usulután', 'Santa Elena'),
    ('Usulután', 'Santa María'),
    ('Usulután', 'Santiago de María'),
    ('Usulután', 'Tecapán')
)
INSERT INTO municipios (departamento_id, nombre)
SELECT d.id, s.municipio
FROM municipios_seed s
JOIN departamentos d ON d.nombre = s.departamento
ON CONFLICT (departamento_id, nombre) DO NOTHING;