// <auto-generated />
using System;
using IguanaSV.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IguanaSV.Api.Migrations
{
    [DbContext(typeof(IguanasDbContext))]
    partial class IguanasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IguanaSV.Api.Entities.Amenidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("amenidades_pkey");

                    b.HasIndex(new[] { "Nombre" }, "amenidades_nombre_key")
                        .IsUnique();

                    b.ToTable("amenidades", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Anfitrione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Verificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verificado");

                    b.HasKey("Id")
                        .HasName("anfitriones_pkey");

                    b.HasIndex(new[] { "Email" }, "anfitriones_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "MunicipioId" }, "idx_anfitriones_municipio");

                    b.ToTable("anfitriones", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("categorias_pkey");

                    b.HasIndex(new[] { "Nombre" }, "categorias_nombre_key")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("departamentos_pkey");

                    b.HasIndex(new[] { "Nombre" }, "departamentos_nombre_key")
                        .IsUnique();

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Experiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("DuracionHoras")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_horas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioAdicional")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_adicional");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("publicacion_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("experiencias_pkey");

                    b.HasIndex(new[] { "PublicacionId" }, "idx_experiencias_publicacion");

                    b.ToTable("experiencias", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<bool?>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("publicacion_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("horarios_pkey");

                    b.HasIndex("PublicacionId", "DiaSemana")
                        .HasDatabaseName("horarios_no_overlap");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PublicacionId", "DiaSemana"), "gist");

                    b.HasIndex(new[] { "PublicacionId" }, "idx_horarios_publicacion");

                    b.ToTable("horarios", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.ImagenesPublicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_principal");

                    b.Property<int?>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("publicacion_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("imagenes_publicacion_pkey");

                    b.HasIndex(new[] { "PublicacionId" }, "idx_imagenes_publicacion_publicacion");

                    b.ToTable("imagenes_publicacion", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("municipios_pkey");

                    b.HasIndex(new[] { "DepartamentoId" }, "idx_municipios_departamento");

                    b.HasIndex(new[] { "DepartamentoId", "Nombre" }, "municipios_departamento_id_nombre_key")
                        .IsUnique();

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Notificacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DestinatarioEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("destinatario_email");

                    b.Property<bool?>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("notificaciones_pkey");

                    b.HasIndex(new[] { "DestinatarioEmail" }, "idx_notificaciones_destinatario");

                    b.HasIndex(new[] { "ReservaId" }, "idx_notificaciones_reserva");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.PublicacionAmenidad", b =>
                {
                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("publicacion_id");

                    b.Property<int>("AmenidadId")
                        .HasColumnType("integer")
                        .HasColumnName("amenidad_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PublicacionId", "AmenidadId")
                        .HasName("publicacion_amenidad_pkey");

                    b.HasIndex("AmenidadId");

                    b.ToTable("publicacion_amenidad", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Publicacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnfitrionId")
                        .HasColumnType("integer")
                        .HasColumnName("anfitrion_id");

                    b.Property<int?>("Banos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("banos");

                    b.Property<int?>("Camas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("camas");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("DireccionExacta")
                        .HasColumnType("text")
                        .HasColumnName("direccion_exacta");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'activo'::character varying");

                    b.Property<int?>("Habitaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("habitaciones");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitud");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_por_noche");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("publicaciones_pkey");

                    b.HasIndex(new[] { "AnfitrionId" }, "idx_publicaciones_anfitrion");

                    b.HasIndex(new[] { "CategoriaId" }, "idx_publicaciones_categoria");

                    b.HasIndex(new[] { "Estado" }, "idx_publicaciones_estado");

                    b.ToTable("publicaciones", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EmailHuesped")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email_huesped");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'pendiente'::character varying");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("NombreHuesped")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_huesped");

                    b.Property<int>("NumeroHuespedes")
                        .HasColumnType("integer")
                        .HasColumnName("numero_huespedes");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_total");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("publicacion_id");

                    b.Property<string>("TelefonoHuesped")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_huesped");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("reservas_pkey");

                    b.HasIndex("PublicacionId")
                        .HasDatabaseName("reservas_no_overlap");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PublicacionId"), "gist");

                    b.HasIndex(new[] { "Estado" }, "idx_reservas_estado");

                    b.HasIndex(new[] { "FechaInicio", "FechaFin" }, "idx_reservas_fechas");

                    b.HasIndex(new[] { "PublicacionId" }, "idx_reservas_publicacion");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.ReservaHorario", b =>
                {
                    b.Property<int>("ReservaId")
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    b.Property<int>("HorarioId")
                        .HasColumnType("integer")
                        .HasColumnName("horario_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ReservaId", "HorarioId")
                        .HasName("reserva_horario_pkey");

                    b.HasIndex("HorarioId");

                    b.HasIndex(new[] { "ReservaId" }, "idx_reserva_horario_reserva");

                    b.ToTable("reserva_horario", (string)null);
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Anfitrione", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Municipio", "Municipio")
                        .WithMany("Anfitriones")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("anfitriones_municipio_id_fkey");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Experiencia", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Publicacione", "Publicacion")
                        .WithMany("Experiencia")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("experiencias_publicacion_id_fkey");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Horario", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Publicacione", "Publicacion")
                        .WithMany("Horarios")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("horarios_publicacion_id_fkey");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.ImagenesPublicacion", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Publicacione", "Publicacion")
                        .WithMany("ImagenesPublicacions")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("imagenes_publicacion_publicacion_id_fkey");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Municipio", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("municipios_departamento_id_fkey");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Notificacione", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Reserva", "Reserva")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notificaciones_reserva_id_fkey");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.PublicacionAmenidad", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Amenidade", "Amenidad")
                        .WithMany("PublicacionAmenidads")
                        .HasForeignKey("AmenidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("publicacion_amenidad_amenidad_id_fkey");

                    b.HasOne("IguanaSV.Api.Entities.Publicacione", "Publicacion")
                        .WithMany("PublicacionAmenidads")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("publicacion_amenidad_publicacion_id_fkey");

                    b.Navigation("Amenidad");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Publicacione", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Anfitrione", "Anfitrion")
                        .WithMany("Publicaciones")
                        .HasForeignKey("AnfitrionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("publicaciones_anfitrion_id_fkey");

                    b.HasOne("IguanaSV.Api.Entities.Categoria", "Categoria")
                        .WithMany("Publicaciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("publicaciones_categoria_id_fkey");

                    b.Navigation("Anfitrion");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Reserva", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Publicacione", "Publicacion")
                        .WithMany("Reservas")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reservas_publicacion_id_fkey");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.ReservaHorario", b =>
                {
                    b.HasOne("IguanaSV.Api.Entities.Horario", "Horario")
                        .WithMany("ReservaHorarios")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reserva_horario_horario_id_fkey");

                    b.HasOne("IguanaSV.Api.Entities.Reserva", "Reserva")
                        .WithMany("ReservaHorarios")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reserva_horario_reserva_id_fkey");

                    b.Navigation("Horario");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Amenidade", b =>
                {
                    b.Navigation("PublicacionAmenidads");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Anfitrione", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Horario", b =>
                {
                    b.Navigation("ReservaHorarios");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Municipio", b =>
                {
                    b.Navigation("Anfitriones");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Publicacione", b =>
                {
                    b.Navigation("Experiencia");

                    b.Navigation("Horarios");

                    b.Navigation("ImagenesPublicacions");

                    b.Navigation("PublicacionAmenidads");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("IguanaSV.Api.Entities.Reserva", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("ReservaHorarios");
                });
#pragma warning restore 612, 618
        }
    }
}
